import type { EvidenceSourceId } from "./types";

export const researchSources: Record<EvidenceSourceId, { citation: string; title: string; url: string; note: string }> = {
  retrieval: { citation: "Roediger & Karpicke (2006)", title: "The Power of Testing Memory", url: "https://www.psychologicalscience.org/journals/perspectives/j.1745-6916.2006.00012.x/", note: "Review of retrieval practice and later retention." },
  workedExamples: { citation: "Sweller & Cooper (1985)", title: "The Use of Worked Examples as a Substitute for Problem Solving in Learning Algebra", url: "https://doi.org/10.1207/s1532690xci0201_3", note: "Experimental evidence for worked examples during early learning." },
  utilityValue: { citation: "Hulleman & Harackiewicz (2009)", title: "Promoting Interest and Performance in High School Science Classes", url: "https://pubmed.ncbi.nlm.nih.gov/19965759/", note: "Randomized field experiment connecting coursework to students' lives." },
  implementation: { citation: "Gollwitzer & Sheeran (2006)", title: "Implementation Intentions and Goal Achievement", url: "https://doi.org/10.1016/S0065-2601%2806%2938002-1", note: "Meta-analysis of 94 tests of specific when, where, and how plans." },
  listening: { citation: "Weger et al. (2014)", title: "The Relative Effectiveness of Active Listening in Initial Interactions", url: "https://doi.org/10.1080/10904018.2013.813234", note: "Experiment comparing active listening, advice, and simple acknowledgements." },
  apology: { citation: "Lewicki, Polin, & Lount (2016)", title: "An Exploration of the Structure of Effective Apologies", url: "https://ncmr.lps.library.cmu.edu/article/id/264/", note: "Two studies comparing components of apologies after trust violations." },
  assertiveness: { citation: "ElBarazi et al. (2024)", title: "Efficiency of Assertiveness Training on College Students", url: "https://pubmed.ncbi.nlm.nih.gov/39268439/", note: "Randomized trial of an eight-session combined skills program with 100 college students." },
  affectLabeling: { citation: "Lieberman et al. (2007)", title: "Putting Feelings Into Words", url: "https://pubmed.ncbi.nlm.nih.gov/17576282/", note: "Laboratory neuroimaging study of affect labeling and emotional reactivity." },
  worry: { citation: "LaFreniere et al. (2025)", title: "Effects of Worry Postponement on Daily Worry and Sleep", url: "https://pubmed.ncbi.nlm.nih.gov/41347618/", note: "Randomized trial; worry postponement was most useful when paired with specific planning." },
  music: { citation: "de Witte et al. (2020)", title: "Effects of Music Interventions on Stress-Related Outcomes", url: "https://pubmed.ncbi.nlm.nih.gov/31167611/", note: "Systematic review and meta-analyses of 104 randomized trials." },
  exercise: { citation: "Carter et al. (2023)", title: "The Effect of Acute Exercise on State Anxiety", url: "https://pubmed.ncbi.nlm.nih.gov/37624125/", note: "Systematic review of randomized trials in healthy adults." },
  selfEfficacy: { citation: "Bandura (1977)", title: "Self-Efficacy: Toward a Unifying Theory of Behavioral Change", url: "https://doi.org/10.1037/0033-295X.84.2.191", note: "Foundational theory describing mastery experience as a source of self-efficacy." },
  monitoring: { citation: "Harkin et al. (2016)", title: "Does Monitoring Goal Progress Promote Goal Attainment?", url: "https://pubmed.ncbi.nlm.nih.gov/26479070/", note: "Meta-analysis of 138 randomized studies on progress monitoring." },
  reflection: { citation: "Fiodorova & Farb (2022)", title: "Brief Daily Self-Care Reflection for Undergraduate Well-Being", url: "https://pubmed.ncbi.nlm.nih.gov/34313502/", note: "Small randomized trial with 95 undergraduates." },
  personalityContext: { citation: "Fleeson (2001)", title: "Traits as Density Distributions of States", url: "https://doi.org/10.1037/0022-3514.80.6.1011", note: "Experience-sampling studies showing substantial within-person variation across situations." },
  youthLeisure: { citation: "Asquith et al. (2022)", title: "Personality Traits, Leisure Activities, and Well-Being in Young People", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9636694/", note: "Observational study of people ages 14 to 20; social and physical activity predicted some well-being outcomes." },
  activityFit: { citation: "Kuper et al. (2023)", title: "Who Benefits From Which Activity?", url: "https://pubmed.ncbi.nlm.nih.gov/36326676/", note: "Eleven-wave observational study; personality did not reliably moderate within-person leisure benefits." },
  selfDetermination: { citation: "Ryan & Deci (2000)", title: "Self-Determination Theory and the Facilitation of Intrinsic Motivation", url: "https://doi.org/10.1037/0003-066X.55.1.68", note: "Foundational review of autonomy, competence, and relatedness." },
};
