import type { ActivityCompletion, ActivityPreferences, GoalKey, Recommendation, TraitKey, TraitScore } from "./types";

export const goals: Array<{ key: GoalKey; label: string; icon: string }> = [
  { key: "studying", label: "Study with less friction", icon: "✦" },
  { key: "relationships", label: "Build stronger relationships", icon: "♡" },
  { key: "stress", label: "Handle stress more gently", icon: "○" },
  { key: "confidence", label: "Grow steady confidence", icon: "↗" },
  { key: "reflection", label: "Understand myself better", icon: "◎" },
];

type Band = TraitScore["band"];
type Tags = NonNullable<Recommendation["preferenceTags"]>;
const all: Band[] = ["lower", "middle", "higher"];
const match = (trait: TraitKey, bands: Band[], reason: string) => ({ trait, bands, reason });
const solo = (interests: ActivityPreferences["interests"], benefits: ActivityPreferences["benefits"], maxMinutes: number, extra: Tags = {}): Tags => ({ settings:["solo"], structures:["starting-point","step-by-step","options"], commitments:["once","monthly","weekly","most-days"], novelties:["familiar","small-change","mixed"], challenges:["easy","small","moderate"], constraints:["free","quiet","private","no-supplies","home","low-energy","no-screen"], interests, benefits, maxMinutes, ...extra });
const social = (interests: ActivityPreferences["interests"], benefits: ActivityPreferences["benefits"], maxMinutes: number, extra: Tags = {}): Tags => ({ settings:["pair","small-group","large-group"], roles:["participant","equal","lead"], structures:["starting-point","options"], commitments:["once","monthly","weekly"], novelties:["familiar","small-change","mixed","new"], challenges:["small","moderate","stretch"], constraints:["free","no-supplies","no-screen"], interests, benefits, maxMinutes, ...extra });

export const activityLibrary: Recommendation[] = [
  // Studying: seven distinct formats
  {id:"study-start",goal:"studying",title:"The ten-minute opening",description:"Choose the smallest visible first step, set a ten-minute timer, and stop or continue when it rings.",why:"A short start can reduce the friction of beginning.",action:"Name one task and its first physical action.",duration:"10 min",traitMatches:[match("conscientiousness",["lower","middle"],"A small cue can add structure without requiring a detailed system.")],preferenceTags:solo(["planning"],["accomplished","skill"],10)},
  {id:"study-environment",goal:"studying",title:"Borrow structure from your environment",description:"Put the next task in sight, set one reminder, and remove one distraction before beginning.",why:"External cues can carry part of the planning load.",action:"Prepare tomorrow’s first task before stopping today.",duration:"8 min",traitMatches:[match("conscientiousness",["lower"],"Flexible external supports may fit better than a complex routine.")],preferenceTags:solo(["planning"],["accomplished","skill"],8,{structures:["step-by-step"]})},
  {id:"study-done",goal:"studying",title:"Define ‘done enough’ first",description:"Write the minimum standard that would make this session worthwhile before you start.",why:"A stopping rule can keep useful standards from expanding indefinitely.",action:"Set one clear finish line for today.",duration:"3 min",traitMatches:[match("conscientiousness",["higher"],"Your organized approach is useful, and a boundary can protect your time.")],preferenceTags:solo(["writing","planning"],["accomplished","understand"],3)},
  {id:"study-body-double",goal:"studying",title:"Work beside someone",description:"Study near one person who is also working. Agree on a check-in time, then work quietly.",why:"Shared presence can provide gentle accountability without constant conversation.",action:"Ask one person for a 25-minute work session.",duration:"30 min",traitMatches:[match("conscientiousness",["lower","middle"],"Light accountability may support follow-through."),match("extraversion",["middle","higher"],"Some social presence may help sustain your energy.")],preferenceTags:social(["social","planning"],["accomplished","connect"],30,{settings:["pair","small-group"],roles:["equal","participant"],constraints:["free","quiet","no-supplies","home"]})},
  {id:"study-curiosity",goal:"studying",title:"Build a curiosity bridge",description:"Connect one required topic to a question, example, or problem you genuinely care about.",why:"Personal relevance can make dry material easier to engage with.",action:"Write one ‘How does this connect to…?’ question.",duration:"10 min",traitMatches:[match("openness",["middle","higher"],"Your curiosity may make connections and questions motivating.")],preferenceTags:solo(["learning","creative","writing"],["skill","fun"],10,{novelties:["mixed","new"]})},
  {id:"study-example",goal:"studying",title:"Start from a worked example",description:"Find one completed example, cover the solution, and recreate each step in your own words.",why:"A concrete model can make an unfamiliar task less vague.",action:"Choose one example and explain its first step.",duration:"15 min",traitMatches:[match("openness",["lower","middle"],"Concrete examples may suit your preference for practical starting points.")],preferenceTags:solo(["learning","planning"],["skill","accomplished"],15,{structures:["step-by-step"],novelties:["familiar","small-change"]})},
  {id:"study-recall",goal:"studying",title:"Five-question recall sprint",description:"Close your notes, write five questions, answer from memory, and then check your answers.",why:"Retrieval practice reveals what you know and what needs another look.",action:"Write the first question without reopening your notes.",duration:"15 min",traitMatches:[match("conscientiousness",["middle","higher"],"A defined challenge can use your preference for purposeful effort.")],preferenceTags:solo(["learning","games"],["skill","accomplished","fun"],15,{settings:["solo","pair","small-group"],challenges:["moderate","stretch"]})},
  {id:"study-parking",goal:"studying",title:"Make a distraction parking lot",description:"When an unrelated thought appears, write it on a nearby list and return to the task.",why:"Recording a thought can make it easier to postpone acting on it.",action:"Place a blank note beside your work area.",duration:"5 min",traitMatches:[match("emotionalStability",["middle","higher"],"A holding place may help when worries compete for attention."),match("openness",["higher"],"It gives new ideas somewhere to go without losing them.")],preferenceTags:solo(["writing","planning"],["calm","accomplished"],5)},

  // Relationships
  {id:"relationship-check",goal:"relationships",title:"Ask before advising",description:"Try: “Do you want ideas, practical help, or just company right now?”",why:"A clear invitation reduces guessing about useful support.",action:"Use the question in one conversation.",duration:"2 min",traitMatches:[match("agreeableness",["middle","higher"],"This builds on your attention to others while keeping support specific.")],preferenceTags:social(["social"],["connect","skill"],2,{settings:["pair","small-group"],roles:["participant","equal"]})},
  {id:"relationship-depth",goal:"relationships",title:"Choose depth over volume",description:"Invite one person into a low-pressure activity with a clear start and end.",why:"Connection does not require a crowded room or an open-ended plan.",action:"Send one specific invitation.",duration:"5 min",traitMatches:[match("extraversion",["lower"],"A smaller, predictable setting may better fit your social energy.")],preferenceTags:social(["social"],["connect","fun"],5,{settings:["pair"],roles:["participant","equal"],novelties:["familiar","small-change"]})},
  {id:"relationship-listen",goal:"relationships",title:"Leave a listening beat",description:"Wait two seconds after someone finishes and ask one follow-up before adding your experience.",why:"A deliberate pause creates more room for the other person.",action:"Try the pause in one conversation today.",duration:"2 min",traitMatches:[match("extraversion",["higher"],"It balances expressive social energy with intentional listening.")],preferenceTags:social(["social"],["connect","skill"],2)},
  {id:"relationship-honesty",goal:"relationships",title:"Pair honesty with a question",description:"Try: “Here’s how I see it. What am I missing?”",why:"Curiosity can help direct communication land without weakening the point.",action:"Use the sentence in one low-stakes discussion.",duration:"3 min",traitMatches:[match("agreeableness",["lower"],"This uses your comfort with candor while keeping the exchange open.")],preferenceTags:social(["social"],["connect","understand"],3,{settings:["pair","small-group"]})},
  {id:"relationship-side",goal:"relationships",title:"Connect side by side",description:"Choose a shared task such as walking, cooking, drawing, or studying instead of making conversation the whole activity.",why:"A shared focus can make connection feel more natural and less pressured.",action:"Pick one familiar activity and invite one person.",duration:"30 min",traitMatches:[match("extraversion",["lower","middle"],"Side-by-side interaction can offer connection without constant conversation."),match("openness",["lower","middle"],"A familiar activity provides a comfortable base.")],preferenceTags:social(["social","movement","creative","outside"],["connect","fun","mood"],30,{settings:["pair","small-group"],roles:["equal","participant"],novelties:["familiar","small-change"],constraints:["free","home","outside","no-screen"]})},
  {id:"relationship-repair",goal:"relationships",title:"Write a three-part repair message",description:"Name what happened, acknowledge its effect, and suggest one next step without defending yourself first.",why:"A short structure can make a difficult repair more manageable.",action:"Draft the message before deciding whether to send it.",duration:"15 min",traitMatches:[match("emotionalStability",["middle","higher"],"Preparing words first may reduce pressure in an emotional conversation."),match("agreeableness",all,"Repair can protect a relationship without ignoring your view.")],preferenceTags:solo(["writing","social"],["connect","express","understand"],15,{settings:["solo","pair"],challenges:["moderate","stretch"]})},
  {id:"relationship-role",goal:"relationships",title:"Choose one group role on purpose",description:"Choose one useful role: start the plan, keep time, invite quieter voices, or take notes.",why:"A chosen role can reduce uncertainty and make participation feel useful.",action:"Pick one role for your next group activity.",duration:"5 min",traitMatches:[match("extraversion",["middle"],"A defined role can help you flex between speaking up and stepping back."),match("agreeableness",["middle"],"It offers a practical balance between cooperation and independence.")],preferenceTags:social(["social","planning"],["connect","skill","accomplished"],5,{settings:["small-group","large-group"]})},
  {id:"relationship-boundary",goal:"relationships",title:"Practice a warm boundary",description:"Use: “I care about this, and I can’t take it on right now.” Adjust it until it sounds like you.",why:"Clear boundaries make care and cooperation more sustainable.",action:"Draft one sentence for a real situation.",duration:"5 min",traitMatches:[match("agreeableness",["middle","higher"],"You may notice others’ needs quickly, so protecting your capacity matters too.")],preferenceTags:solo(["writing","social"],["connect","express","accomplished"],5,{settings:["solo","pair"]})},

  // Stress
  {id:"stress-ground",goal:"stress",title:"Name five neutral things",description:"Notice five things you see, four you feel, and three you hear without judging them.",why:"Directing attention to the environment may help you feel more present.",action:"Save this sequence for a stressful transition.",duration:"3 min",traitMatches:[match("emotionalStability",["middle","higher"],"A short grounding option may help when stress becomes noticeable.")],preferenceTags:solo(["mindfulness"],["calm","distract"],3,{structures:["step-by-step"]})},
  {id:"stress-label",goal:"stress",title:"Name what you feel",description:"Name the feeling, rate its intensity, and identify what you need in the next ten minutes.",why:"Putting feelings into words can create distance from an intense reaction.",action:"Write: “Right now I notice…”",duration:"5 min",traitMatches:[match("emotionalStability",["higher"],"Your answers suggest you may notice stress reactions quickly or strongly.")],preferenceTags:solo(["writing","mindfulness"],["calm","express","understand"],5)},
  {id:"stress-signals",goal:"stress",title:"Check the quiet signals",description:"Scan your sleep, jaw, shoulders, appetite, and focus before deciding you are fine.",why:"Stress can appear through body signals even when emotions feel steady.",action:"Choose one signal to notice this week.",duration:"3 min",traitMatches:[match("emotionalStability",["lower"],"Because you may stay calm under pressure, quieter signs can be easier to miss.")],preferenceTags:solo(["mindfulness"],["calm","understand"],3)},
  {id:"stress-window",goal:"stress",title:"Schedule a worry window",description:"Write worries as they arise and choose a later 15-minute period to review only those still relevant.",why:"A planned time can keep worry from taking every available moment.",action:"Choose today’s window and make a one-line list.",duration:"15 min",traitMatches:[match("emotionalStability",["higher"],"A container may help when worry returns often."),match("conscientiousness",["middle","higher"],"A scheduled approach may fit your preference for structure.")],preferenceTags:solo(["writing","planning"],["calm","understand"],15,{challenges:["small","moderate"]})},
  {id:"stress-music",goal:"stress",title:"Build a three-song reset",description:"Choose one song that meets your mood, one that steadies it, and one that moves it where you want.",why:"An intentional sequence can provide a predictable transition.",action:"Add the three songs to one playlist.",duration:"15 min",traitMatches:[match("openness",all,"Music offers a flexible way to work with mood without needing many words.")],preferenceTags:solo(["music"],["calm","mood","energy","distract"],15,{settings:["solo","pair"],structures:["step-by-step","options"]})},
  {id:"stress-move",goal:"stress",title:"Move for one song",description:"Walk, stretch, shake out tension, or dance until one song ends. Intensity is optional.",why:"Brief movement can interrupt a tense transition and change physical state.",action:"Choose the easiest movement you would actually do.",duration:"5 min",traitMatches:[match("emotionalStability",["middle","higher"],"A body-based option may help when stress feels physical."),match("extraversion",["middle","higher"],"Active stimulation may fit your energy style.")],preferenceTags:solo(["movement","music","outside"],["calm","mood","energy","fun"],5,{settings:["solo","pair","small-group"],constraints:["free","home","outside","no-supplies","no-screen"]})},
  {id:"stress-control",goal:"stress",title:"Sort what you can control",description:"Make three columns: control, influence, and cannot control. Place each current stressor in one.",why:"Sorting can direct effort toward what is actionable.",action:"Choose one item from the control column.",duration:"10 min",traitMatches:[match("conscientiousness",["middle","higher"],"A clear framework may help organize competing demands."),match("emotionalStability",["middle","higher"],"It separates action from uncertainty when stress rises.")],preferenceTags:solo(["writing","planning"],["calm","understand","accomplished"],10,{structures:["step-by-step"]})},
  {id:"stress-comfort",goal:"stress",title:"Make a low-demand comfort menu",description:"List five familiar activities that require little decision-making, then circle the easiest one.",why:"A prepared menu reduces choices when energy is low.",action:"Write five realistic options for home or outside.",duration:"10 min",traitMatches:[match("openness",["lower","middle"],"Familiar routines may feel more settling than novelty during stress."),match("emotionalStability",["middle","higher"],"A ready list can help when decisions feel harder.")],preferenceTags:solo(["planning","writing"],["calm","mood","distract"],10,{novelties:["familiar","small-change"]})},

  // Confidence
  {id:"confidence-proof",goal:"confidence",title:"Keep a proof file",description:"Record one effort, brave choice, or small follow-through each day, not just outcomes.",why:"Specific memories make your ability to act and recover easier to remember.",action:"Add your first example now.",duration:"4 min",traitMatches:[match("conscientiousness",all,"Tracking concrete follow-through can make progress visible.")],preferenceTags:solo(["writing"],["accomplished","understand"],4)},
  {id:"confidence-no",goal:"confidence",title:"Practice a warm no",description:"Use: “I care about this, and I can’t take it on right now.”",why:"A respectful boundary can strengthen confidence in your own limits.",action:"Draft one sentence for a real situation.",duration:"5 min",traitMatches:[match("agreeableness",["higher"],"Your cooperative style is a strength, and boundaries keep it sustainable.")],preferenceTags:solo(["writing","social"],["accomplished","connect","express"],5,{settings:["solo","pair"]})},
  {id:"confidence-familiar",goal:"confidence",title:"Stretch from something familiar",description:"Change one part of a routine you already know instead of beginning from a blank page.",why:"Growth can start from stability rather than novelty for its own sake.",action:"Pick one ten-percent change.",duration:"5 min",traitMatches:[match("openness",["lower"],"A familiar base may make a new step feel more credible.")],preferenceTags:solo(["planning","learning"],["accomplished","skill"],5,{novelties:["familiar","small-change"]})},
  {id:"confidence-ladder",goal:"confidence",title:"Make a brave-reps ladder",description:"List easy, medium, and stretch versions of one action. Start with the easiest version.",why:"Confidence often grows from repeated experience, not waiting for certainty.",action:"Complete the easiest rung within 24 hours.",duration:"15 min",traitMatches:[match("emotionalStability",["middle","higher"],"Graduated steps can make an intimidating action more manageable.")],preferenceTags:solo(["planning","games"],["accomplished","skill"],15,{settings:["solo","pair"],structures:["step-by-step","options"],challenges:["small","moderate","stretch"]})},
  {id:"confidence-feedback",goal:"confidence",title:"Ask for one specific strength",description:"Ask someone you trust when they have seen you handle something well. Request one example.",why:"Outside observations can reveal strengths that are hard to notice alone.",action:"Choose one person and send the question.",duration:"10 min",traitMatches:[match("extraversion",["middle","higher"],"Conversation may be a useful way to gather perspective."),match("agreeableness",["middle","higher"],"Trusted relationships may be a comfortable source of feedback.")],preferenceTags:social(["social","learning"],["connect","understand","accomplished"],10,{settings:["pair"]})},
  {id:"confidence-decision",goal:"confidence",title:"Use a decision timer",description:"Give a low-stakes choice five minutes. List two priorities, choose, and do not reopen it for a day.",why:"A time boundary turns indecision into practice trusting your judgment.",action:"Pick one choice that does not need perfect certainty.",duration:"5 min",traitMatches:[match("conscientiousness",["higher"],"A stopping rule can keep careful thinking from becoming endless review."),match("emotionalStability",["middle","higher"],"A low-stakes limit may reduce room for spiraling.")],preferenceTags:solo(["planning","games"],["accomplished","understand"],5,{structures:["step-by-step"]})},
  {id:"confidence-lead",goal:"confidence",title:"Lead one small piece",description:"In a shared activity, volunteer for one bounded task instead of taking responsibility for everything.",why:"A contained leadership experience can build confidence without making stakes too high.",action:"Choose one task you can own from start to finish.",duration:"30 min",traitMatches:[match("extraversion",["middle","higher"],"A visible social role may fit your interpersonal energy."),match("agreeableness",["middle"],"A bounded role balances contribution with your limits.")],preferenceTags:social(["social","planning"],["accomplished","connect","skill"],30,{roles:["lead","equal"]})},
  {id:"confidence-create",goal:"confidence",title:"Finish a tiny creation",description:"Make something small enough to complete today, then show it to one safe person or keep a dated copy.",why:"A visible artifact provides evidence of action, not just intention.",action:"Choose a sketch, playlist, photo, recipe, poem, or mini project.",duration:"60 min",traitMatches:[match("openness",["middle","higher"],"Creative variety may make practice more personally meaningful.")],preferenceTags:solo(["creative","music","writing","learning"],["express","fun","accomplished","skill"],60,{settings:["solo","pair"],novelties:["mixed","new"],challenges:["moderate","stretch"]})},

  // Reflection
  {id:"reflect-context",goal:"reflection",title:"Where does this trait help?",description:"Choose one result and name a setting where it helps, plus one where you adjust it.",why:"Context keeps a trait score from becoming a fixed label.",action:"Complete both halves of the sentence.",duration:"6 min",traitMatches:[match("openness",all,"Comparing contexts can make a broad trait result more personally useful.")],preferenceTags:solo(["writing","learning"],["understand","express"],6,{settings:["solo","pair"]})},
  {id:"reflect-experiment",goal:"reflection",title:"Turn one idea into an experiment",description:"Choose one interesting idea and test the smallest real version within 48 hours.",why:"A tiny experiment turns reflection into information from real life.",action:"Write the idea, test, and deadline.",duration:"7 min",traitMatches:[match("openness",["higher"],"Your curiosity may generate possibilities that become clearer through testing.")],preferenceTags:solo(["creative","learning","planning"],["understand","skill","accomplished"],7,{settings:["solo","pair"],novelties:["mixed","new"],challenges:["moderate","stretch"]})},
  {id:"reflect-week",goal:"reflection",title:"Review three moments from the week",description:"Choose one easy moment, one difficult moment, and one surprise. Note what was different.",why:"Real moments can reveal patterns without requiring a daily journal.",action:"Write one sentence for each moment.",duration:"15 min",traitMatches:[match("conscientiousness",["middle","higher"],"A repeatable review may fit your organized reflection style."),match("openness",["middle"],"It balances curiosity with concrete examples.")],preferenceTags:solo(["writing","planning"],["understand","accomplished"],15,{structures:["step-by-step"]})},
  {id:"reflect-energy",goal:"reflection",title:"Map what gives and takes energy",description:"Mark five recent activities as energizing, neutral, or draining.",why:"Observed energy patterns can be more useful than assumptions about what you should enjoy.",action:"Circle one activity to add, reduce, or change.",duration:"10 min",traitMatches:[match("extraversion",all,"This distinguishes your actual social and solitary energy patterns from a label.")],preferenceTags:solo(["writing","planning"],["understand","energy"],10)},
  {id:"reflect-values",goal:"reflection",title:"Sort ten values",description:"Choose ten values, narrow them to five, then pick two you want your next month to reflect.",why:"Priorities become clearer when useful values have to compete.",action:"Start with ten words that matter to you.",duration:"20 min",traitMatches:[match("agreeableness",["lower","middle"],"This can clarify which priorities are yours rather than simply shared by a group."),match("openness",["middle","higher"],"Exploring meaning may fit your reflective curiosity.")],preferenceTags:solo(["writing","learning","games"],["understand","express"],20,{settings:["solo","pair","small-group"],structures:["step-by-step","options"]})},
  {id:"reflect-stress",goal:"reflection",title:"Trace one stress reaction",description:"Write what happened, what you thought, what you felt, what you did, and what helped.",why:"Separating the parts of a reaction can make future choices easier to notice.",action:"Use one recent, manageable example.",duration:"15 min",traitMatches:[match("emotionalStability",["middle","higher"],"Your stress response may become clearer when viewed in parts.")],preferenceTags:solo(["writing","mindfulness"],["understand","calm","express"],15,{structures:["step-by-step"]})},
  {id:"reflect-feedback",goal:"reflection",title:"Compare your view with trusted feedback",description:"Ask one person for a strength and growth area, then compare their examples with your own view.",why:"Two perspectives can reveal both blind spots and misunderstandings.",action:"Choose a person who can be honest and kind.",duration:"30 min",traitMatches:[match("agreeableness",["middle","higher"],"A trusted conversation may feel like a natural way to learn."),match("extraversion",["middle","higher"],"Interactive reflection may hold your attention better than solitary writing.")],preferenceTags:social(["social","learning"],["understand","connect","skill"],30,{settings:["pair"]})},
  {id:"reflect-remix",goal:"reflection",title:"Run a one-week routine experiment",description:"Change one element of a routine for a week and track whether it helps, hurts, or makes no difference.",why:"A controlled change produces personal evidence without rebuilding everything.",action:"Choose the routine, one change, and one thing to observe.",duration:"10 min",traitMatches:[match("openness",["lower","middle"],"A small change preserves familiarity while making room to learn."),match("conscientiousness",["middle"],"A simple experiment balances structure with flexibility.")],preferenceTags:solo(["planning","learning","games"],["understand","skill","accomplished"],10,{commitments:["weekly","most-days"],novelties:["small-change","mixed"]})},
];

function availableMinutes(preferences: ActivityPreferences) {
  return preferences.time === "depends" || preferences.time === "over-60" ? Infinity : Number(preferences.time);
}

function traitFit(item: Recommendation, scores: TraitScore[]) {
  return (item.traitMatches || []).reduce((sum, rule) => {
    const result = scores.find((score) => score.trait === rule.trait);
    return sum + (result && rule.bands.includes(result.band) ? 8 : 0);
  }, 0);
}

function preferenceFit(item: Recommendation, preferences?: ActivityPreferences) {
  if (!preferences || !item.preferenceTags) return 0;
  const tags = item.preferenceTags;
  let score = preferences.setting === "depends" ? 1 : tags.settings?.includes(preferences.setting) ? 5 : -4;
  if (preferences.setting !== "solo" && preferences.role !== "no-preference") score += tags.roles?.includes(preferences.role) ? 2 : -1;
  score += preferences.structure === "unsure" ? 1 : tags.structures?.includes(preferences.structure) ? 3 : -1;
  if (preferences.commitment !== "depends" && tags.commitments?.includes(preferences.commitment)) score += 2;
  score += preferences.novelty === "no-preference" ? 1 : tags.novelties?.includes(preferences.novelty) ? 2 : -1;
  score += preferences.challenge === "depends" ? 1 : tags.challenges?.includes(preferences.challenge) ? 3 : -2;
  score += preferences.benefits.includes("none") ? 1 : preferences.benefits.filter((value) => tags.benefits?.includes(value)).length * 3;
  score += preferences.interests.includes("open") ? 1 : preferences.interests.filter((value) => tags.interests?.includes(value)).length * 4;
  const constraints = preferences.constraints.filter((value) => value !== "none");
  score += constraints.filter((value) => tags.constraints?.includes(value)).length * 2;
  score -= constraints.filter((value) => !tags.constraints?.includes(value)).length * 5;
  score += (tags.maxMinutes || 0) <= availableMinutes(preferences) ? 5 : -12;
  return score;
}

function feedbackFit(item: Recommendation, history: ActivityCompletion[] = []) {
  return history.reduce((score, completion) => {
    const completed = activityLibrary.find((entry) => entry.id === completion.activityId);
    if (!completed?.preferenceTags || !item.preferenceTags) return score;
    const sharedInterests = completed.preferenceTags.interests?.some((value) => item.preferenceTags?.interests?.includes(value));
    const sharedBenefits = completed.preferenceTags.benefits?.some((value) => item.preferenceTags?.benefits?.includes(value));
    const similarFormat = sharedInterests || sharedBenefits;
    if (completion.helpful === "yes") score += similarFormat ? 4 : 0;
    if (completion.helpful === "somewhat") score += similarFormat ? 2 : 0;
    if (completion.helpful === "no") score -= similarFormat ? 4 : 0;
    if (completion.similar === "yes") score += similarFormat ? 5 : 0;
    if (completion.similar === "maybe") score += similarFormat ? 2 : 0;
    if (completion.similar === "no") score -= similarFormat ? 5 : 0;
    const desiredChallenges = completion.nextStep === "higher" ? ["moderate", "stretch"] : completion.nextStep === "easier" ? ["easy", "small"] : [];
    if (desiredChallenges.some((value) => item.preferenceTags?.challenges?.includes(value as ActivityPreferences["challenge"]))) score += 4;
    return score;
  }, 0);
}

export function getRecommendations(scores: TraitScore[], goal: GoalKey, preferences?: ActivityPreferences, history: ActivityCompletion[] = []) {
  return activityLibrary.filter((item) => item.goal === goal).map((item,index)=>({item,index,score:traitFit(item,scores)+preferenceFit(item,preferences)+feedbackFit(item,history)})).sort((a,b)=>b.score-a.score||a.index-b.index).map(({item})=>item);
}

export function describeRecommendationReason(item: Recommendation, scores: TraitScore[], preferences?: ActivityPreferences) {
  const traitReason = item.traitMatches?.find((rule) => { const score=scores.find((entry)=>entry.trait===rule.trait); return score&&rule.bands.includes(score.band); })?.reason;
  const fits: string[] = [];
  if (preferences && item.preferenceTags) {
    if ((item.preferenceTags.maxMinutes||0)<=availableMinutes(preferences)) fits.push("the time you have");
    if (preferences.interests.includes("open")||preferences.interests.some((value)=>item.preferenceTags?.interests?.includes(value))) fits.push("your interests");
    if (preferences.setting==="depends"||item.preferenceTags.settings?.includes(preferences.setting)) fits.push("your preferred setting");
    if (preferences.benefits.includes("none")||preferences.benefits.some((value)=>item.preferenceTags?.benefits?.includes(value))) fits.push("what you want from an activity");
  }
  return [traitReason||item.why,fits.length?`It also fits ${fits.slice(0,2).join(" and ")}.`:""].filter(Boolean).join(" ");
}
