import type { ActivityCompletion, ActivityPreferences, EvidenceLevel, EvidenceSourceId, GoalKey, Recommendation, TraitScore } from "./types";

export const goals: Array<{ key: GoalKey; label: string; icon: string }> = [
  { key: "studying", label: "Study with less friction", icon: "✦" },
  { key: "relationships", label: "Build stronger relationships", icon: "♡" },
  { key: "stress", label: "Handle stress more gently", icon: "○" },
  { key: "confidence", label: "Grow steady confidence", icon: "↗" },
  { key: "reflection", label: "Understand myself better", icon: "◎" },
];

type Tags = NonNullable<Recommendation["preferenceTags"]>;
const solo = (interests: ActivityPreferences["interests"], benefits: ActivityPreferences["benefits"], maxMinutes: number, extra: Tags = {}): Tags => ({ settings:["solo"], structures:["starting-point","step-by-step","options"], commitments:["once","monthly","weekly","most-days"], novelties:["familiar","small-change","mixed"], challenges:["easy","small","moderate"], constraints:["free","quiet","private","no-supplies","home","low-energy","no-screen"], interests, benefits, maxMinutes, ...extra });
const social = (interests: ActivityPreferences["interests"], benefits: ActivityPreferences["benefits"], maxMinutes: number, extra: Tags = {}): Tags => ({ settings:["pair","small-group","large-group"], roles:["participant","equal","lead"], structures:["starting-point","options"], commitments:["once","monthly","weekly"], novelties:["familiar","small-change","mixed","new"], challenges:["small","moderate","stretch"], constraints:["free","no-supplies","no-screen"], interests, benefits, maxMinutes, ...extra });
const evidence = (level: EvidenceLevel, summary: string, limitation: string, ...sources: EvidenceSourceId[]) => ({ level, summary, limitation, sources });

export const activityLibrary: Recommendation[] = [
  {id:"study-recall",goal:"studying",title:"Five-question recall sprint",description:"Close your notes, write five questions, answer from memory, and then check your answers.",why:"Retrieval practice helps strengthen later recall.",action:"Write the first question without reopening your notes.",duration:"15 min",evidence:evidence("strong","Retrieving information from memory improves later retention compared with restudying.","The studies support retrieval practice broadly, not exactly five questions or a 15-minute session.","retrieval"),preferenceTags:solo(["learning","games"],["skill","accomplished","fun"],15,{settings:["solo","pair","small-group"],challenges:["moderate","stretch"]})},
  {id:"study-example",goal:"studying",title:"Learn from a worked example",description:"Study one completed example, cover the solution, and recreate each step in your own words.",why:"A concrete model can reduce unnecessary mental load while a skill is still unfamiliar.",action:"Choose one example and explain its first step.",duration:"15 min",evidence:evidence("strong","Worked examples can improve early learning of structured problem-solving tasks.","Evidence is strongest for novices learning procedural material such as algebra.","workedExamples"),preferenceTags:solo(["learning","planning"],["skill","accomplished"],15,{structures:["step-by-step"],novelties:["familiar","small-change"]})},
  {id:"study-relevance",goal:"studying",title:"Make a relevance connection",description:"Connect one required topic to your life, a goal, or a problem you genuinely care about.",why:"Finding personal usefulness can increase interest in course material.",action:"Finish: “This could matter to me because…”",duration:"10 min",evidence:evidence("promising","A randomized high-school study found benefits from writing about the personal relevance of science material.","Benefits were strongest for students with lower expectations of success and may not generalize to every subject.","utilityValue"),preferenceTags:solo(["learning","writing","creative"],["skill","fun","understand"],10)},
  {id:"study-if-then",goal:"studying",title:"Make an if-then start plan",description:"Choose a specific cue and response: “If it is 7:00 and I am at my desk, then I will open my notes and answer one question.”",why:"Specific situation-response plans can make starting more automatic.",action:"Write one realistic if-then sentence.",duration:"4 min",evidence:evidence("strong","A large meta-analysis found that implementation intentions improved goal attainment.","The research supports specific cue-response plans, not guaranteed academic improvement.","implementation"),preferenceTags:solo(["planning","writing"],["accomplished","skill"],4,{structures:["step-by-step"]})},
  {id:"study-progress",goal:"studying",title:"End with a progress note",description:"After studying, record what you completed and the next action you will take.",why:"Written progress monitoring can support follow-through.",action:"Write one completed step and one next step.",duration:"3 min",evidence:evidence("strong","A meta-analysis of 138 studies found that progress monitoring promoted goal attainment.","The review covered many goal areas; this exact study note was not tested separately.","monitoring"),preferenceTags:solo(["writing","planning"],["accomplished","understand"],3)},
  {id:"study-choice",goal:"studying",title:"Choose your study route",description:"Pick one of three evidence-based starts: recall questions, a worked example, or a relevance connection.",why:"A meaningful choice can support autonomy while keeping the options useful.",action:"Choose the option you are most willing to start now.",duration:"15 min",evidence:evidence("contextual","Self-determination research identifies autonomy and competence as important for motivation.","This theory does not show that a three-option menu improves grades by itself.","selfDetermination","retrieval","workedExamples","utilityValue"),preferenceTags:solo(["learning","planning"],["skill","accomplished"],15,{structures:["options"]})},

  {id:"relationship-listen",goal:"relationships",title:"Listen, reflect, then ask",description:"Reflect the main thing you heard and ask one follow-up before offering your own experience.",why:"Active-listening responses can help another person feel understood.",action:"Try: “It sounds like ____. What was that like for you?”",duration:"3 min",evidence:evidence("promising","An experiment found that active listening increased speakers' feeling of being understood.","The study examined initial conversations, not every type of close relationship or conflict.","listening"),preferenceTags:social(["social"],["connect","skill"],3,{settings:["pair"]})},
  {id:"relationship-ask",goal:"relationships",title:"Ask what kind of support would help",description:"Ask whether the person wants listening, ideas, or practical help before responding.",why:"The question makes room for responsive support instead of guessing.",action:"Try: “Would listening, ideas, or practical help feel best?”",duration:"2 min",evidence:evidence("promising","Active listening and responsive support research emphasize understanding the speaker's needs.","The exact three-option question has not been tested as a stand-alone intervention.","listening"),preferenceTags:social(["social"],["connect","skill"],2,{settings:["pair"]})},
  {id:"relationship-repair",goal:"relationships",title:"Draft a repair message",description:"Acknowledge what you did, recognize its effect, and offer one realistic repair without defending yourself first.",why:"Responsibility and an offer of repair are important components of effective apologies.",action:"Draft the message before deciding whether to send it.",duration:"15 min",evidence:evidence("promising","Experimental apology research found that acknowledging responsibility and offering repair increased perceived effectiveness.","The studies used trust-violation scenarios; real relationships and serious harm are more complex.","apology"),preferenceTags:solo(["writing","social"],["connect","express","understand"],15,{settings:["solo","pair"],challenges:["moderate","stretch"]})},
  {id:"relationship-boundary",goal:"relationships",title:"Practice one clear boundary",description:"State what you can or cannot do, briefly and respectfully, without adding a long defense.",why:"Assertiveness combines clarity about your needs with respect for the other person.",action:"Draft: “I can’t ____, but I can ____.”",duration:"5 min",evidence:evidence("promising","A randomized college study found benefits from a multi-session program that included assertiveness practice.","The program also included mindfulness and problem-solving, so the effect cannot be assigned to this sentence alone.","assertiveness"),preferenceTags:solo(["writing","social"],["connect","express","accomplished"],5,{settings:["solo","pair"]})},
  {id:"relationship-shared",goal:"relationships",title:"Plan a shared activity",description:"Invite someone you trust to walk, exercise, study, or do another familiar activity together.",why:"Socializing and physical activity are associated with several aspects of well-being in young people.",action:"Send one specific, low-pressure invitation.",duration:"30 min",evidence:evidence("contextual","Studies of young people and long-term leisure patterns link social and physical activities with some well-being outcomes.","These studies are mainly observational and do not prove that one invitation will improve well-being.","youthLeisure","activityFit"),preferenceTags:social(["social","movement","outside"],["connect","fun","mood"],30,{settings:["pair","small-group"]})},
  {id:"relationship-choice",goal:"relationships",title:"Choose a connection that fits",description:"Pick a brief message, one-to-one conversation, or shared activity based on what feels realistic today.",why:"Choice and relatedness can support willing participation rather than forced socializing.",action:"Choose the smallest form of connection you genuinely want.",duration:"5 min",evidence:evidence("contextual","Self-determination theory identifies autonomy and relatedness as basic psychological needs.","It is a broad motivational framework, not a direct test of this activity menu.","selfDetermination"),preferenceTags:social(["social"],["connect"],5,{settings:["pair","small-group"],structures:["options"]})},

  {id:"stress-label",goal:"stress",title:"Name what you feel",description:"Name the feeling and rate its intensity without trying to argue with it.",why:"Putting feelings into words may reduce immediate emotional reactivity.",action:"Write: “I notice ____ at about ____ out of 10.”",duration:"3 min",evidence:evidence("promising","A laboratory neuroimaging study found reduced limbic responses during affect labeling.","This demonstrates an immediate neural mechanism, not lasting stress reduction or treatment effectiveness.","affectLabeling"),preferenceTags:solo(["writing","mindfulness"],["calm","express","understand"],3)},
  {id:"stress-window",goal:"stress",title:"Plan a short worry period",description:"When a worry appears, note it and use a specific if-then plan for a later 15-minute review.",why:"Postponement appears more useful when paired with clear planning.",action:"Write when, where, and how you will review the list.",duration:"15 min",evidence:evidence("promising","A randomized trial found lower worry duration for worry postponement paired with implementation planning.","Worry postponement alone was less convincing, and sleep did not improve.","worry","implementation"),preferenceTags:solo(["writing","planning"],["calm","understand"],15,{challenges:["small","moderate"]})},
  {id:"stress-music",goal:"stress",title:"Take a music reset",description:"Listen to music you find calming or steadying without multitasking for one or two songs.",why:"Music interventions have shown small-to-moderate average effects on stress outcomes.",action:"Choose music that feels settling rather than what you think should work.",duration:"10 min",evidence:evidence("strong","Meta-analyses of 104 randomized trials found improvements in psychological and physiological stress outcomes.","Studies varied widely, and results do not identify one best song, genre, or playlist order.","music"),preferenceTags:solo(["music"],["calm","mood","distract"],10,{settings:["solo","pair"]})},
  {id:"stress-move",goal:"stress",title:"Try a brief movement break",description:"Walk, stretch, dance, or do another safe movement at a comfortable intensity.",why:"A single bout of exercise can reduce state anxiety on average.",action:"Choose a movement you can stop or adjust at any time.",duration:"10 min",evidence:evidence("strong","Systematic reviews of randomized studies support acute exercise for state anxiety and stress reactivity.","Effects vary, and the evidence does not establish one ideal activity or duration for everyone.","exercise"),preferenceTags:solo(["movement","outside"],["calm","mood","energy"],10,{settings:["solo","pair","small-group"],constraints:["free","home","outside","no-supplies","no-screen"]})},
  {id:"stress-connect",goal:"stress",title:"Choose one supportive connection",description:"Ask someone you trust for a short check-in, shared activity, or quiet company.",why:"Social activity and relatedness are associated with well-being in young people.",action:"Ask for the kind and length of connection you want.",duration:"10 min",evidence:evidence("contextual","Observational youth research links social activity with positive affect, mental health, and flourishing; self-determination theory emphasizes relatedness.","These sources do not prove that a single check-in reduces acute stress.","youthLeisure","selfDetermination"),preferenceTags:social(["social"],["connect","calm"],10,{settings:["pair","small-group"]})},
  {id:"stress-reflect",goal:"stress",title:"Do a brief self-care check",description:"Notice what supported you today and choose one realistic action for tomorrow.",why:"Brief repeated reflection may help prevent stress and negative affect from accumulating.",action:"Write one thing that helped and one plan for tomorrow.",duration:"5 min",evidence:evidence("promising","A small randomized study found reduced stress and negative affect after three weeks of daily self-care reflection.","The sample was 95 undergraduates and used repeated daily prompts, not a one-time exercise.","reflection"),preferenceTags:solo(["writing","planning"],["calm","understand"],5)},

  {id:"confidence-ladder",goal:"confidence",title:"Build a mastery ladder",description:"List easy, medium, and stretch versions of one safe action, then start with the easy version.",why:"Manageable mastery experiences are a foundational source of self-efficacy.",action:"Complete the easiest step and record what happened.",duration:"15 min",evidence:evidence("contextual","Self-efficacy theory identifies successful mastery experiences as especially influential.","This is foundational theory; the exact three-rung activity has not been independently tested.","selfEfficacy"),preferenceTags:solo(["planning","games"],["accomplished","skill"],15,{settings:["solo","pair"],structures:["step-by-step","options"],challenges:["small","moderate","stretch"]})},
  {id:"confidence-proof",goal:"confidence",title:"Record evidence of progress",description:"Write one specific action you completed, what helped, and the next manageable step.",why:"Physically recording progress can support goal attainment.",action:"Add one example from today.",duration:"4 min",evidence:evidence("strong","A meta-analysis found that progress monitoring improved goal attainment, especially when progress was recorded.","The review studied goal attainment, not confidence as a stand-alone outcome.","monitoring"),preferenceTags:solo(["writing","planning"],["accomplished","understand"],4)},
  {id:"confidence-assert",goal:"confidence",title:"Rehearse an assertive request",description:"State what you need clearly, give a brief reason if useful, and leave room for the other person to respond.",why:"Assertiveness can be practiced as a communication skill.",action:"Draft and say one low-stakes request aloud.",duration:"8 min",evidence:evidence("promising","A randomized college trial found improved assertiveness and reduced distress after a combined skills program.","The intervention involved eight group sessions, so a single rehearsal should not be expected to reproduce its effects.","assertiveness"),preferenceTags:solo(["writing","social"],["express","accomplished","skill"],8,{settings:["solo","pair"]})},
  {id:"confidence-create",goal:"confidence",title:"Finish one small, chosen task",description:"Choose something useful or meaningful that is small enough to finish today.",why:"Completion can provide a mastery experience, while choice supports autonomy.",action:"Define a finish line that fits the time you have.",duration:"30 min",evidence:evidence("contextual","Self-efficacy and self-determination research support mastery, competence, and autonomy as motivational principles.","The exact task and confidence outcome have not been tested as one intervention.","selfEfficacy","selfDetermination"),preferenceTags:solo(["creative","learning","planning"],["accomplished","skill","fun"],30,{settings:["solo","pair"]})},
  {id:"confidence-active",goal:"confidence",title:"Choose an active leisure step",description:"Pick a physical or social activity you already find acceptable and make the next step specific.",why:"Physical and social leisure are associated with several well-being outcomes in young people.",action:"Choose the activity, time, place, and first step.",duration:"30 min",evidence:evidence("contextual","Youth studies associate physical and social leisure with positive affect, mental health, or flourishing.","The findings are observational, effects are generally small, and personality did not reliably determine who benefited.","youthLeisure","activityFit"),preferenceTags:social(["movement","social","outside"],["mood","connect","accomplished"],30)},
  {id:"confidence-plan",goal:"confidence",title:"Turn a goal into an if-then plan",description:"Choose a safe action and connect it to a clear time, place, or event.",why:"Specific implementation plans can improve the chance of acting on a goal.",action:"Write: “If ____, then I will ____.”",duration:"4 min",evidence:evidence("strong","A meta-analysis found a medium-to-large average effect of implementation intentions on goal attainment.","Goal completion is not the same as a guaranteed increase in confidence.","implementation"),preferenceTags:solo(["planning","writing"],["accomplished","skill"],4)},

  {id:"reflect-context",goal:"reflection",title:"Notice how context changes you",description:"Choose one trait and compare how it appears in two different settings.",why:"People show substantial trait-relevant variation across everyday situations.",action:"Complete: “In ____ I tend to ____, while in ____ I tend to ____.”",duration:"8 min",evidence:evidence("strong","Experience-sampling studies found substantial within-person variation in Big Five-related states.","The research supports the contextual view of traits, not a proven benefit from this worksheet.","personalityContext"),preferenceTags:solo(["writing","learning"],["understand","express"],8,{settings:["solo","pair"]})},
  {id:"reflect-week",goal:"reflection",title:"Review support and strain",description:"Choose one moment that supported you and one that drained you, then identify one difference between them.",why:"Repeated self-care reflection may help reduce accumulating stress and negative affect.",action:"Write one observation and one realistic adjustment.",duration:"10 min",evidence:evidence("promising","A randomized undergraduate study found benefits from three weeks of brief daily self-care reflection.","This weekly two-moment format was not the exact intervention tested.","reflection"),preferenceTags:solo(["writing","planning"],["understand","calm"],10)},
  {id:"reflect-track",goal:"reflection",title:"Track activity and well-being",description:"For one week, record one activity and whether you felt better, worse, or unchanged afterward.",why:"Your own repeated observations are more useful than assuming a trait guarantees an activity will help.",action:"Choose one activity category and one simple rating.",duration:"5 min",evidence:evidence("contextual","Longitudinal leisure research found small, highly variable links between activities and well-being, with little evidence that personality determined within-person benefits.","Self-tracking cannot establish causation and may miss delayed or outside influences.","activityFit","youthLeisure"),preferenceTags:solo(["writing","planning"],["understand","mood"],5,{commitments:["weekly","most-days"]})},
  {id:"reflect-progress",goal:"reflection",title:"Run one small goal experiment",description:"Choose one action, make a specific if-then plan, and record whether it happened.",why:"Planning and progress monitoring are both supported self-regulation strategies.",action:"Write the cue, action, and check-in date.",duration:"7 min",evidence:evidence("strong","Meta-analyses support implementation intentions and recorded progress monitoring for goal attainment.","This does not guarantee the chosen action is beneficial; keep the experiment low-risk.","implementation","monitoring"),preferenceTags:solo(["planning","learning","games"],["understand","skill","accomplished"],7)},
  {id:"reflect-needs",goal:"reflection",title:"Check autonomy, competence, and connection",description:"Ask which need feels most supported right now: choice, capability, or connection with others.",why:"These three needs are central in self-determination theory.",action:"Choose one need and one small way to support it.",duration:"8 min",evidence:evidence("contextual","Self-determination theory links autonomy, competence, and relatedness with motivation and well-being.","This check-in is an application of the theory, not a separately validated assessment or intervention.","selfDetermination"),preferenceTags:solo(["writing","planning"],["understand","accomplished","connect"],8,{settings:["solo","pair"]})},
  {id:"reflect-choice",goal:"reflection",title:"Choose what you are willing to repeat",description:"Compare two completed activities and choose which one felt more useful, meaningful, or realistic.",why:"Your preference and actual response are more defensible guides than a personality stereotype.",action:"Name one activity to repeat and one reason.",duration:"5 min",evidence:evidence("contextual","Activity-fit and self-determination research support attending to preference, autonomy, and lived response.","Evidence for perfectly matching people to activities is limited, and effects differ across individuals.","activityFit","selfDetermination"),preferenceTags:solo(["writing","planning"],["understand","accomplished"],5)},
];

function availableMinutes(preferences: ActivityPreferences) {
  return preferences.time === "depends" || preferences.time === "over-60" ? Infinity : Number(preferences.time);
}

function preferenceFit(item: Recommendation, preferences?: ActivityPreferences) {
  if (!preferences || !item.preferenceTags) return 0;
  const tags = item.preferenceTags;
  let score = preferences.setting === "depends" ? 1 : tags.settings?.includes(preferences.setting) ? 5 : -4;
  if (preferences.setting !== "solo" && preferences.role !== "no-preference") score += tags.roles?.includes(preferences.role) ? 2 : -1;
  score += preferences.structure === "unsure" ? 1 : tags.structures?.includes(preferences.structure) ? 3 : -1;
  if (preferences.commitment !== "depends" && tags.commitments?.includes(preferences.commitment)) score += 2;
  score += preferences.novelty === "no-preference" ? 1 : tags.novelties?.includes(preferences.novelty) ? 2 : -1;
  score += preferences.challenge === "depends" ? 1 : tags.challenges?.includes(preferences.challenge) ? 3 : -2;
  score += preferences.benefits.includes("none") ? 1 : preferences.benefits.filter((value) => tags.benefits?.includes(value)).length * 3;
  score += preferences.interests.includes("open") ? 1 : preferences.interests.filter((value) => tags.interests?.includes(value)).length * 4;
  const constraints = preferences.constraints.filter((value) => value !== "none");
  score += constraints.filter((value) => tags.constraints?.includes(value)).length * 2;
  score -= constraints.filter((value) => !tags.constraints?.includes(value)).length * 5;
  score += (tags.maxMinutes || 0) <= availableMinutes(preferences) ? 5 : -12;
  return score;
}

function feedbackFit(item: Recommendation, history: ActivityCompletion[] = []) {
  return history.reduce((score, completion) => {
    const completed = activityLibrary.find((entry) => entry.id === completion.activityId);
    if (!completed?.preferenceTags || !item.preferenceTags) return score;
    const sharedInterests = completed.preferenceTags.interests?.some((value) => item.preferenceTags?.interests?.includes(value));
    const sharedBenefits = completed.preferenceTags.benefits?.some((value) => item.preferenceTags?.benefits?.includes(value));
    const similarFormat = sharedInterests || sharedBenefits;
    if (completion.helpful === "yes") score += similarFormat ? 4 : 0;
    if (completion.helpful === "somewhat") score += similarFormat ? 2 : 0;
    if (completion.helpful === "no") score -= similarFormat ? 4 : 0;
    if (completion.similar === "yes") score += similarFormat ? 5 : 0;
    if (completion.similar === "maybe") score += similarFormat ? 2 : 0;
    if (completion.similar === "no") score -= similarFormat ? 5 : 0;
    const desiredChallenges = completion.nextStep === "higher" ? ["moderate", "stretch"] : completion.nextStep === "easier" ? ["easy", "small"] : [];
    if (desiredChallenges.some((value) => item.preferenceTags?.challenges?.includes(value as ActivityPreferences["challenge"]))) score += 4;
    return score;
  }, 0);
}

export function getRecommendations(_scores: TraitScore[], goal: GoalKey, preferences?: ActivityPreferences, history: ActivityCompletion[] = []) {
  return activityLibrary.filter((item) => item.goal === goal).map((item,index)=>({item,index,score:preferenceFit(item,preferences)+feedbackFit(item,history)})).sort((a,b)=>b.score-a.score||a.index-b.index).map(({item})=>item);
}

export function describeRecommendationReason(item: Recommendation, _scores: TraitScore[], preferences?: ActivityPreferences) {
  const fits: string[] = [];
  if (preferences && item.preferenceTags) {
    if ((item.preferenceTags.maxMinutes||0)<=availableMinutes(preferences)) fits.push("the time you have");
    if (preferences.interests.includes("open")||preferences.interests.some((value)=>item.preferenceTags?.interests?.includes(value))) fits.push("your interests");
    if (preferences.setting==="depends"||item.preferenceTags.settings?.includes(preferences.setting)) fits.push("your preferred setting");
    if (preferences.benefits.includes("none")||preferences.benefits.some((value)=>item.preferenceTags?.benefits?.includes(value))) fits.push("what you want from an activity");
  }
  return [item.why,fits.length?`It also fits ${fits.slice(0,2).join(" and ")}.`:""].filter(Boolean).join(" ");
}
